### ISSUE TITLE
Cannot download Wordpress plugin on site

### ISSUE THREAD

**Issue by jxs714** [markustenghamn/WHMCS-Affiliates-Anywhere#1]
Hi Markus,

Hope you're well. Tried downloading the Wordpress plugin on the anveto site as mentioned in the readme, but the site gives the following error:

> Downloading this item requires you to have an active instance of the following product/service:
> Anveto Affiliate Anywhere Plus Unencoded

There is no way to download the Wordpress plugin on site even after trying to do any free purchases. Also, will the Anveto plus work on the latest WHMCS 7.1.1 and Wordpress plugin work on the latest Wordpress 4.7?

Please advise, thanks!

**Comment by uberswe** [comment]
I will create another repository on github for the Wordpress plugin when I get home tonight and update the readme. Thanks for bringing it to my attention.

I have not had time to test this on 7.1.1 but it should work.

**Comment by jxs714** [comment]
Hi Markus,

Thanks for reaching back very quickly and for the support! Looking forward to it. Upon testing, I will be sure to reach out if any issues or incompatibility. Will also let you know if its working good as well :)

**Comment by uberswe** [comment]
Thanks! I really appreciate it.

I have added the Wordpress plugin here https://github.com/markustenghamn/WHMCS-Affiliates-Anywhere-Wordpress

**Comment by jxs714** [comment]
Hi Markus,

Thanks so much for the update and consistency! Keep up the great work :)
